### PR TITLE
Add backoff on connection retries

### PR DESCRIPTION
**Pull request by vshlapakov**
The PR adds simple backoff logic to add optional delay for connection retries.

Review, please.

[Review on Reviewable](https://reviewable.io/reviews/orionvm/potsdb/4)

### CODE REVIEW

**Comment by mcclymont** [comment]
Hi. Can you please explain why you think this retry delay is needed? Did you encounter a situation where it retried very often?

If needed, I think it would be better to just include a mandatory retry delay of a few seconds rather than adding a configuration option.

**Comment by vshlapakov** [comment]
Hi @mcclymont Of course, sorry for being too brief. 

My usecase is a distributed system with `collectd` + `potsdb` when OpenTSDB instance can be down (due to maintenance, for example), and not having backoff on retries looks pretty harmful for the system. I don't mind if this delay will be fixed, as you wish! Usually people want to have an ability to tune everything :)

**Comment by mcclymont** [comment]
I've implemented a simple exponential backoff instead 0fb0bbf674b1c5d8a0cd67dedd5699b3c838d461. Released in v1.0.3. Thanks for your input.

**Comment by vshlapakov** [comment]
Thanks @mcclymont!

**Pull request closed without merging**
